name: Test
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.on }}
    strategy:
      matrix:
        include:
          - { environment: "sagemath-109", on: "ubuntu-24.04" }
    steps:
      - uses: actions/checkout@v6
        with: { submodules: recursive }
      - uses: prefix-dev/setup-pixi@v0.9.3
        with: { pixi-version: v0.42.1 }
      - run: pixi run -e ${{ matrix.environment }} test-doctest-long
      - run: pixi run -e ${{ matrix.environment }} test-pytest
      - uses: flatsurf/actions/show-logs@main
        if: ${{ always() }}
